/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#10131a",
        "surface-dim": "#10131a",
        "surface-bright": "#363941",
        "surface-container-lowest": "#0b0e15",
        "surface-container-low": "#191b23",
        "surface-container": "#191C22",
        "surface-container-high": "#272a31",
        "surface-container-highest": "#32353c",
        "on-surface": "#e0e2ec",
        "on-surface-variant": "#c1c7d2",
        outline: "#8b919b",
        "outline-variant": "#414750",
        primary: "#9dcaff",
        "on-primary": "#003257",
        "primary-container": "#5195d8",
        secondary: "#c2c6d5",
        "on-secondary": "#2b303c",
        "secondary-container": "#424753",
        tertiary: "#fdba4f",
        "on-tertiary": "#442b00",
        "tertiary-container": "#c0851c",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        background: "#10131a",
        "on-background": "#e0e2ec",
        "surface-variant": "#32353c",
        "status-green": "#2FA84F",
        "status-red": "#D64545",
        "status-amber": "#C98A2C",
        "ui-border": "#232833",
        "active-focus": "#3B82C4",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};
